accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import forms, views

app_name = 'accounts'

urlpatterns = [
    path('privacy/', TemplateView.as_view(template_name='accounts/privacy.html'), name='privacy'),
    path('tos/', TemplateView.as_view(template_name='accounts/tos.html'), name='tos'),
    path('register/', views.register, name='register'),
    path(
        'login/',
        auth_views.LoginView.as_view(
            template_name='accounts/login.html',
            authentication_form=forms.LoginForm,
            redirect_authenticated_user=True,
            next_page='fido:new-shelter',
        ),
        name='login',
    ),
    path('logout/', auth_views.LogoutView.as_view(next_page='fido:homepage'), name='logout'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('fido.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = TemplateView.as_view(template_name='403.html')
handler404 = TemplateView.as_view(template_name='404.html')

fido/urls.py
from django.urls import path
from django.views.generic import TemplateView

from fido import views

app_name = 'fido'

urlpatterns = [
    path('', TemplateView.as_view(template_name='fido/index.html'), name='homepage'),
    path('for-shelters/', TemplateView.as_view(template_name='fido/for-shelters.html'), name='for-shelters'),
    path('contact/', views.contact, name='contact'),
    path('cat/<int:pk>/', views.cat_page, name='cat'),
    path('dog/<int:pk>/', views.dog_page, name='dog'),
    path('search/cats/', views.search_cats, name='search-cats'),
    path('search/dogs/', views.search_dogs, name='search-dogs'),
    path('search/cats/<slug:breed>/<slug:age>/<slug:sex>/<slug:shelter__shelteraddress__state>/',
         views.search_cats_params),
    path('search/dogs/<slug:breed>/<slug:age>/<slug:sex>/<slug:shelter__shelteraddress__state>/',
         views.search_dogs_params),
    path('shelter/<int:pk>/', views.shelter_page, name='shelter'),
    path('shelter/new/', views.new_shelter, name='new-shelter'),
    path('shelter/edit/', views.edit_shelter, name='edit-shelter'),
    path('shelter/remove/', views.remove_shelter, name='remove-shelter'),
    path('shelter/pets/', views.manage_pets, name='manage-pets'),
    path('shelter/cat/new/', views.new_cat, name='new-cat'),
    path('shelter/dog/new/', views.new_dog, name='new-dog'),
    path('shelter/cat/<int:pk>/edit/', views.edit_cat, name='edit-cat'),
    path('shelter/dog/<int:pk>/edit/', views.edit_dog, name='edit-dog'),
    path('shelter/cat/<int:pk>/remove/', views.remove_cat, name='remove-cat'),
    path('shelter/dog/<int:pk>/remove/', views.remove_dog, name='remove-dog'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('Users require an email field')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    first_name = None
    last_name = None
    email = models.EmailField(unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from common.forms.models import StyledForm, StyledModelForm
from .models import User


class NewUserForm(StyledModelForm, UserCreationForm):
    consent = forms.BooleanField()

    class Meta:
        model = User
        fields = ['email', 'password1', 'password2', 'consent']


class LoginForm(StyledForm, AuthenticationForm):
    pass

accounts/views.py
from django.contrib.auth import login
from django.shortcuts import redirect, render

from .forms import NewUserForm


def register(request):
    if request.user.is_authenticated:
        return redirect('fido:new-shelter')
    if request.method == 'POST':
        form = NewUserForm(request.POST)
        if form.is_valid():
            login(request, user=form.save())
            return redirect('fido:new-shelter')
        return render(request, 'accounts/register.html', {'form': form})
    return render(request, 'accounts/register.html', {'form': NewUserForm()})

templates/accounts/login.html
{% extends 'base.html' %}
{% block title %}
    Log in | {{ block.super }}
{% endblock title %}
{% block navbar %}{% endblock navbar %}
{% block content %}
    <section class="min-vh-100 d-flex align-items-center bg-soft">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 d-flex align-items-center justify-content-center">
                    <div class="mt-3 mt-lg-0 bg-white shadow-soft border rounded border-light p-4 p-lg-5 w-100 fmxw-500">
                        <div class="text-center text-md-center mb-4 mt-md-0">
                            <h1 class="mb-0 h3">Log in to our platform</h1>
                        </div>
                        <form method="POST" class="mt-4">
                            {% csrf_token %}
                            <div class="form-group">
                                {{ form.username.label_tag }}
                                <div class="input-group mb-4">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">
                                            <span class="fas fa-envelope"></span>
                                        </span>
                                    </div>
                                    {{ form.username }}
                                </div>
                                {{ form.username.errors }}
                            </div>
                            <div class="form-group">
                                <div class="form-group">
                                    {{ form.password.label_tag }}
                                    <div class="input-group mb-4">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text">
                                                <span class="fas fa-unlock-alt"></span>
                                            </span>
                                        </div>
                                        {{ form.password }}
                                    </div>
                                    {{ form.password.errors }}
                                </div>
                            </div>
                            {{ form.non_field_errors }}
                            <button type="submit" class="btn btn-block btn-primary">Log in</button>
                        </form>
                        <div class="d-block text-center mt-4">
                            <span class="font-weight-normal">
                                Not registered?
                                <a href="{% url 'accounts:register' %}" class="font-weight-bold">Create an account</a>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}
{% block footer %}{% endblock footer %}

templates/accounts/privacy.html
{% extends 'base.html' %}
{% block title %}
    Privacy policy | {{ block.super }}
{% endblock title %}
{% block content %}
    <div class="section section-xl bg-primary overflow-hidden">
        <div class="container z-2">
            <div class="row pb-4 pb-md-6 pb-1 justify-content-center text-white text-center">
                <div class="col-12 col-md-10">
                    <div class="mb-3">
                        <h1 class="display-3 font-size-md-down-5 font-weight-light mb-0">
                            Privacy Policy
                        </h1>
                    </div>
                    <p class="my-4 px-0 px-lg-7">Effective 11/02/2022</p>
                </div>
            </div>
        </div>
    </div>
    <div class="section section-xl">
        <div class="container">
            <div class="row justify-content-center text-center">
                <div class="col-12 col-md-10">
                    {% lorem 15 p %}
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/accounts/register.html
{% extends 'base.html' %}
{% block title %}
    Sign up | {{ block.super }}
{% endblock title %}
{% block navbar %}{% endblock navbar %}
{% block content %}
    <section class="min-vh-100 d-flex align-items-center bg-soft">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 d-flex align-items-center justify-content-center">
                    <div class="mt-3 mt-lg-0 bg-white shadow-soft border rounded border-light p-4 p-lg-5 w-100 fmxw-500">
                        <div class="text-center text-md-center mb-4 mt-md-0">
                            <h1 class="mb-0 h3">Create an account</h1>
                        </div>
                        <form method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                {{ form.email.label_tag }}
                                <div class="input-group mb-4">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">
                                            <span class="fas fa-envelope"></span>
                                        </span>
                                    </div>
                                    {{ form.email }}
                                </div>
                                {{ form.email.errors }}
                            </div>
                            <div class="form-group">
                                <div class="form-group">
                                    {{ form.password1.label_tag }}
                                    <div class="input-group mb-4">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text">
                                                <span class="fas fa-unlock-alt"></span>
                                            </span>
                                        </div>
                                        {{ form.password1 }}
                                    </div>
                                    {{ form.password1.errors }}
                                </div>
                                <div class="form-group">
                                    {{ form.password2.label_tag }}
                                    <div class="input-group mb-4">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text">
                                                <span class="fas fa-unlock-alt"></span>
                                            </span>
                                        </div>
                                        {{ form.password2 }}
                                    </div>
                                    {{ form.password2.errors }}
                                </div>
                                <div class="form-check mb-4">
                                    <input class="form-check-input" type="checkbox" name="{{ form.consent.html_name }}"
                                           id="{{ form.consent.id_for_label }}"
                                            {% if form.consent.value %} checked {% endif %}
                                           required>
                                    <label class="form-check-label" for="{{ form.consent.id_for_label }}">
                                        I agree to the
                                        <a href="{% url 'accounts:tos' %}" target="_blank" class="font-weight-bold">
                                            terms of service
                                        </a>
                                        and the
                                        <a href="{% url 'accounts:privacy' %}" target="_blank" class="font-weight-bold">
                                            privacy policy
                                        </a>
                                    </label>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-block btn-primary">Sign up</button>
                        </form>
                        <div class="d-block text-center mt-4">
                            <span class="font-weight-normal">
                                Already have an account?
                                <a href="{% url 'accounts:login' %}" class="font-weight-bold">Log in here</a>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}
{% block footer %}{% endblock footer %}

templates/accounts/tos.html
{% extends 'base.html' %}
{% block title %}
    Terms of Service | {{ block.super }}
{% endblock title %}
{% block content %}
    <div class="section section-xl bg-primary overflow-hidden">
        <div class="container z-2">
            <div class="row pb-4 pb-md-6 pb-1 justify-content-center text-white text-center">
                <div class="col-12 col-md-10">
                    <div class="mb-3">
                        <h1 class="display-3 font-size-md-down-5 font-weight-light mb-0">
                            Terms of Service
                        </h1>
                    </div>
                    <p class="my-4 px-0 px-lg-7">Effective 11/02/2022</p>
                </div>
            </div>
        </div>
    </div>
    <div class="section section-xl">
        <div class="container">
            <div class="row justify-content-center text-center">
                <div class="col-12 col-md-10">
                    {% lorem 15 p %}
                </div>
            </div>
        </div>
    </div>
{% endblock content %}