config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('fido.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = TemplateView.as_view(template_name='403.html')
handler404 = TemplateView.as_view(template_name='404.html')

fido/urls.py
from django.urls import path
from django.views.generic import TemplateView

from fido import views

app_name = 'fido'

urlpatterns = [
    path('', TemplateView.as_view(template_name='fido/index.html'), name='homepage'),
    path('for-shelters/', TemplateView.as_view(template_name='fido/for-shelters.html'), name='for-shelters'),
    path('contact/', views.contact, name='contact'),
    path('cat/<int:pk>/', views.cat_page, name='cat'),
    path('dog/<int:pk>/', views.dog_page, name='dog'),
    path('search/cats/', views.search_cats, name='search-cats'),
    path('search/dogs/', views.search_dogs, name='search-dogs'),
    path('search/cats/<slug:breed>/<slug:age>/<slug:sex>/<slug:shelter__shelteraddress__state>/',
         views.search_cats_params),
    path('search/dogs/<slug:breed>/<slug:age>/<slug:sex>/<slug:shelter__shelteraddress__state>/',
         views.search_dogs_params),
    path('shelter/<int:pk>/', views.shelter_page, name='shelter'),
    path('shelter/new/', views.new_shelter, name='new-shelter'),
    path('shelter/edit/', views.edit_shelter, name='edit-shelter'),
    path('shelter/remove/', views.remove_shelter, name='remove-shelter'),
    path('shelter/pets/', views.manage_pets, name='manage-pets'),
    path('shelter/cat/new/', views.new_cat, name='new-cat'),
    path('shelter/dog/new/', views.new_dog, name='new-dog'),
    path('shelter/cat/<int:pk>/edit/', views.edit_cat, name='edit-cat'),
    path('shelter/dog/<int:pk>/edit/', views.edit_dog, name='edit-dog'),
    path('shelter/cat/<int:pk>/remove/', views.remove_cat, name='remove-cat'),
    path('shelter/dog/<int:pk>/remove/', views.remove_dog, name='remove-dog'),
]

fido/models.py
from django.db import models

from accounts.models import User
from common.constants import CAT_AGE_RANGES, CAT_BREEDS, DOG_AGE_RANGES, DOG_BREEDS, SEXES, US_STATES


class Message(models.Model):
    name = models.CharField(max_length=15)
    email = models.EmailField()
    message = models.TextField()


class Shelter(models.Model):
    name = models.CharField(max_length=15)
    description = models.TextField()
    phone = models.CharField(max_length=12)
    email = models.EmailField()
    website = models.URLField()
    owner = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class ShelterAddress(models.Model):
    street = models.CharField(max_length=50)
    city = models.CharField(max_length=30)
    state = models.CharField(max_length=14, choices=US_STATES, default=US_STATES[0][0])
    zip_code = models.CharField(max_length=10)
    shelter = models.OneToOneField(Shelter, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Shelter addresses'
        indexes = [models.Index(fields=['state', 'shelter'])]

    def __str__(self):
        return f'{self.street}, {self.city}, {self.state} {self.zip_code}'


class Pet(models.Model):
    name = models.CharField(max_length=15)
    description = models.TextField()
    photo = models.ImageField()
    sex = models.CharField(max_length=6, choices=SEXES, default=SEXES[0][0])
    shelter = models.ForeignKey(Shelter, on_delete=models.CASCADE)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class Cat(Pet):
    age = models.CharField(max_length=6, choices=CAT_AGE_RANGES, default=CAT_AGE_RANGES[0][0])
    breed = models.CharField(max_length=13, choices=CAT_BREEDS, default=CAT_BREEDS[0][0])

    class Meta:
        indexes = [models.Index(fields=['sex', 'shelter', 'age', 'breed'])]


class Dog(Pet):
    age = models.CharField(max_length=6, choices=DOG_AGE_RANGES, default=DOG_AGE_RANGES[0][0])
    breed = models.CharField(max_length=18, choices=DOG_BREEDS, default=DOG_BREEDS[0][0])

    class Meta:
        indexes = [models.Index(fields=['sex', 'shelter', 'age', 'breed'])]

fido/forms.py
from django import forms

from common.constants import US_STATES
from common.forms.models import StyledModelForm
from .models import Message, Cat, Dog, Shelter, ShelterAddress


class ContactForm(StyledModelForm):
    class Meta:
        model = Message
        fields = ['name', 'email', 'message']


class SearchPetsForm(StyledModelForm):
    shelter__shelteraddress__state = forms.ChoiceField(choices=US_STATES, label='State')

    class Meta:
        fields = ['breed', 'age', 'sex', 'shelter__shelteraddress__state']


class SearchCatsForm(SearchPetsForm):
    class Meta(SearchPetsForm.Meta):
        model = Cat


class SearchDogsForm(SearchPetsForm):
    class Meta(SearchPetsForm.Meta):
        model = Dog


class ShelterForm(StyledModelForm):
    class Meta:
        model = Shelter
        fields = ['name', 'description', 'phone', 'email', 'website']


class ShelterAddressForm(StyledModelForm):
    class Meta:
        model = ShelterAddress
        fields = ['street', 'city', 'zip_code', 'state']


class PetForm(StyledModelForm):
    class Meta:
        fields = ['name', 'description', 'photo', 'breed', 'age', 'sex']


class CatForm(PetForm):
    class Meta(PetForm.Meta):
        model = Cat


class DogForm(PetForm):
    class Meta(PetForm.Meta):
        model = Dog


class EditPetForm(StyledModelForm):
    photo = forms.ImageField(required=False, widget=forms.FileInput)

    def clean(self):
        if not self.cleaned_data['photo']:
            self.cleaned_data.pop('photo')
        super().clean()


class EditCatForm(EditPetForm, CatForm):
    pass


class EditDogForm(EditPetForm, DogForm):
    pass

fido/views.py
from itertools import chain

from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied, SuspiciousOperation
from django.core.paginator import Paginator
from django.shortcuts import redirect, render, get_object_or_404

from common.constants import APPROX_CAT_COUNT, APPROX_DOG_COUNT, PETS_PER_PAGE
from common.decorators import redirect_if_shelter, shelter_required
from .forms import (ContactForm, CatForm, DogForm, EditCatForm, EditDogForm, SearchCatsForm,
                    SearchDogsForm, ShelterAddressForm, ShelterForm)
from .models import Cat, Dog, Shelter, ShelterAddress


def contact(request):
    if request.method == 'POST':
        return contact_post(request)
    return contact_get(request)


def contact_get(request):
    context = {'form': ContactForm()}
    return render(request, 'fido/contact.html', context)


def contact_post(request):
    form = ContactForm(request.POST)
    if form.is_valid():
        form.save()
        context = {'form': ContactForm(), 'sent': True}
    else:
        context = {'form': form, 'sent': False}
    return render(request, 'fido/contact.html', context)


def cat_page(request, pk):
    return pet_page(request, pk, Cat)


def dog_page(request, pk):
    return pet_page(request, pk, Dog)


def pet_page(request, pk, model):
    context = {'pet': get_object_or_404(model, pk=pk)}
    return render(request, 'fido/pet.html', context)


def search_cats(request):
    context = {
        'form': SearchCatsForm(),
        'pet_url': 'fido:cat',
        'name_plural': 'cats',
        'approx_pet_count': APPROX_CAT_COUNT,
    }
    return search_pets(request, Cat, context)


def search_dogs(request):
    context = {
        'form': SearchDogsForm(),
        'pet_url': 'fido:dog',
        'name_plural': 'dogs',
        'approx_pet_count': APPROX_DOG_COUNT,
    }
    return search_pets(request, Dog, context)


def search_pets(request, model, context):
    pets = model.objects.all().order_by('-pk')
    page_obj = Paginator(pets, PETS_PER_PAGE).get_page(request.GET.get('page'))
    context.update(page_obj=page_obj)
    return render(request, 'fido/search-pets.html', context)


def search_cats_params(request, **params):
    context = {
        'pet_url': 'fido:cat',
        'name_plural': 'cats',
        'approx_pet_count': APPROX_CAT_COUNT,
    }
    return search_pets_params(request, Cat, SearchCatsForm, context, **params)


def search_dogs_params(request, **params):
    context = {
        'pet_url': 'fido:dog',
        'name_plural': 'dogs',
        'approx_pet_count': APPROX_DOG_COUNT,
    }
    return search_pets_params(request, Dog, SearchDogsForm, context, **params)


def search_pets_params(request, model, form_class, context, **params):
    params = {k: v.replace('-', ' ') for k, v in params.items()}
    form = form_class(data=params)
    if not form.is_valid():
        raise SuspiciousOperation
    pets = model.objects.filter(**params).select_related('shelter__shelteraddress').order_by('-pk')
    page_obj = Paginator(pets, PETS_PER_PAGE).get_page(request.GET.get('page'))
    context.update(form=form, page_obj=page_obj)
    return render(request, 'fido/search-pets.html', context)


def shelter_page(request, pk):
    shelter = get_object_or_404(Shelter.objects.select_related('shelteraddress'), pk=pk)
    context = {
        'shelter': shelter,
        'address': shelter.shelteraddress,
        'page_obj': page_obj_all_pets(request, shelter),
    }
    return render(request, 'fido/shelter.html', context)


def page_obj_all_pets(request, shelter):
    cats = Cat.objects.filter(shelter=shelter)
    dogs = Dog.objects.filter(shelter=shelter)
    # cats.union(dogs) makes Dogs appear to be Cats and breaks a custom filter
    pets = sorted(chain(cats, dogs), key=lambda pet: -pet.pk)
    return Paginator(pets, PETS_PER_PAGE).get_page(request.GET.get('page'))


@login_required
@redirect_if_shelter
def new_shelter(request):
    context = {'title': 'New shelter', 'headline': 'Shelter Details'}
    if request.method == 'POST':
        return new_shelter_post(request, context)
    return new_shelter_get(request, context)


def new_shelter_get(request, context):
    context.update(forms=[ShelterForm(), ShelterAddressForm()])
    return render(request, 'fido/form.html', context)


def new_shelter_post(request, context):
    shelter_form = ShelterForm(request.POST)
    address_form = ShelterAddressForm(request.POST)
    if shelter_form.is_valid() and address_form.is_valid():
        shelter = shelter_form.save(commit=False)
        address = address_form.save(commit=False)
        shelter.owner = request.user
        address.shelter = shelter
        shelter.save()
        address.save()
        return redirect('fido:shelter', pk=shelter.pk)
    context.update(forms=[shelter_form, address_form])
    return render(request, 'fido/form.html', context)


@login_required
@shelter_required
def edit_shelter(request):
    context = {'title': 'Manage shelter', 'headline': 'Shelter Details'}
    if request.method == 'POST':
        return edit_shelter_post(request, context)
    return edit_shelter_get(request, context)


def edit_shelter_get(request, context):
    shelter = Shelter.objects.filter(owner=request.user).select_related('shelteraddress')
    shelter_form = ShelterForm(instance=shelter.first())
    address_form = ShelterAddressForm(instance=shelter.first().shelteraddress)
    context.update(forms=[shelter_form, address_form])
    return render(request, 'fido/form.html', context)


def edit_shelter_post(request, context):
    shelter_form = ShelterForm(request.POST)
    address_form = ShelterAddressForm(request.POST)
    if shelter_form.is_valid() and address_form.is_valid():
        shelter = Shelter.objects.filter(owner=request.user)
        address = ShelterAddress.objects.filter(shelter=shelter.first())
        shelter.update(**shelter_form.cleaned_data)
        address.update(**address_form.cleaned_data)
        return redirect('fido:shelter', pk=shelter.first().pk)
    context.update(forms=[shelter_form, address_form])
    return render(request, 'fido/form.html', context)


@login_required
@shelter_required
def remove_shelter(request):
    if request.method == 'POST':
        return remove_shelter_post(request)
    return remove_shelter_get(request)


def remove_shelter_get(request):
    shelter = request.user.shelter
    cat_count = Cat.objects.filter(shelter=shelter).count()
    dog_count = Dog.objects.filter(shelter=shelter).count()
    context = {'shelter': shelter, 'count': cat_count + dog_count}
    return render(request, 'fido/remove-shelter.html', context)


def remove_shelter_post(request):
    request.user.shelter.delete()
    return redirect('fido:homepage')


@login_required
@shelter_required
def manage_pets(request):
    page_obj = page_obj_all_pets(request, request.user.shelter)
    return render(request, 'fido/manage-pets.html', {'page_obj': page_obj})


def new_cat(request):
    context = {'title': 'New cat', 'headline': 'Cat Details'}
    return new_pet(request, CatForm, 'fido:cat', context)


def new_dog(request):
    context = {'title': 'New dog', 'headline': 'Dog Details'}
    return new_pet(request, DogForm, 'fido:dog', context)


@login_required
@shelter_required
def new_pet(request, form_class, pet_url, context):
    if request.method == 'POST':
        return new_pet_post(request, form_class, pet_url, context)
    return new_pet_get(request, form_class, context)


def new_pet_get(request, form_class, context):
    context.update(forms=[form_class()])
    return render(request, 'fido/form.html', context)


def new_pet_post(request, form_class, pet_url, context):
    form = form_class(request.POST, request.FILES)
    if form.is_valid():
        pet = form.save(commit=False)
        pet.shelter = request.user.shelter
        pet.save()
        return redirect(pet_url, pk=pet.pk)
    context.update(forms=[form])
    return render(request, 'fido/form.html', context)


def edit_cat(request, pk):
    context = {'title': 'Edit cat', 'headline': 'Cat Details'}
    return edit_pet(request, pk, Cat, EditCatForm, 'fido:cat', context)


def edit_dog(request, pk):
    context = {'title': 'Edit dog', 'headline': 'Dog Details'}
    return edit_pet(request, pk, Dog, EditDogForm, 'fido:dog', context)


@login_required
@shelter_required
def edit_pet(request, pk, model, form_class, pet_url, context):
    pet = get_object_or_404(model, pk=pk)
    if pet.shelter != request.user.shelter:
        raise PermissionDenied
    if request.method == 'POST':
        return edit_pet_post(request, pk, model, form_class, pet_url, context)
    return edit_pet_get(request, pet, form_class, context)


def edit_pet_get(request, pet, form_class, context):
    context.update(forms=[form_class(instance=pet)])
    return render(request, 'fido/form.html', context)


def edit_pet_post(request, pk, model, form_class, pet_url, context):
    form = form_class(request.POST, request.FILES)
    if form.is_valid():
        pet = model.objects.filter(pk=pk)
        pet.update(**form.cleaned_data)
        return redirect(pet_url, pk=pk)
    context.update(forms=[form])
    return render(request, 'fido/form.html', context)


def remove_cat(request, pk):
    return remove_pet(request, pk, Cat)


def remove_dog(request, pk):
    return remove_pet(request, pk, Dog)


@login_required
@shelter_required
def remove_pet(request, pk, model):
    pet = get_object_or_404(model, pk=pk)
    if pet.shelter != request.user.shelter:
        raise PermissionDenied
    if request.method == 'POST':
        pet.delete()
        return redirect('fido:manage-pets')
    return render(request, 'fido/remove-pet.html', {'pet': pet})

templates/fido/form.html
{% extends 'base.html' %}
{% block title %}
    {{ title }} | {{ block.super }}
{% endblock title %}
{% block content %}
    <section class="section section-header pb-8 bg-primary text-white">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-xl-8 text-center">
                    <h1 class="display-2">{{ headline }}</h1>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container mt-n7 mb-6">
            <div class="row justify-content-center">
                <div class="col-12 d-flex align-items-center justify-content-center">
                    <div class="mt-lg-0 bg-white border rounded border-light p-4 p-lg-5 w-100 fmxw-750">
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% for form in forms %}
                                {% for field in form %}
                                    <div class="form-group">
                                        {{ field.label_tag }}
                                        <div class="input-group mb-4">
                                            {{ field }}
                                        </div>
                                        {{ field.errors }}
                                    </div>
                                {% endfor %}
                            {% endfor %}
                            <button type="submit" class="btn btn-block btn-primary">Save</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

templates/fido/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <section class="section-header bg-primary text-white">
        <div class="container">
            <div class="row justify-content-between align-items-center">
                <div class="col-12 col-md-7 col-lg-6 text-center text-md-left">
                    <h1 class="display-2 mb-4">
                        Looking for
                        <br class="d-none d-md-inline">
                        your dream pet?
                    </h1>
                    <p class="lead mb-4 text-muted">
                        Search among tens of thousands of cats and dogs by sex, breed, or location.
                        All of them with photos!
                    </p>
                    <a href="{% url 'fido:search-cats' %}" class="btn btn-outline-white mr-3">
                        <span class="fas fa-cat mr-2"></span>
                        Cats
                    </a>
                    <a href="{% url 'fido:search-dogs' %}" class="btn btn-outline-white">
                        <span class="fas fa-dog mr-2"></span>
                        Dogs
                    </a>
                </div>
                <div class="col-12 col-md-5 d-none d-md-block text-center">
                    <img class="invert-colors" src="{% static 'fido/images/dog-cat.svg' %}" alt="dog and cat">
                </div>
            </div>
        </div>
    </section>
    <section class="section section-lg">
        <div class="container">
            <div class="row align-items-center justify-content-around">
                <div class="col-md-6 col-xl-6 my-5 mt-sm-0 d-none d-sm-block">
                    <img class="rounded img-fluid effect-img-1 img-shadow" alt="a couple with a dog"
                         src="{% static 'fido/images/couple-dog.jpg' %}">
                    <img class="rounded img-fluid effect-img-2 img-shadow" alt="a girl with a dog"
                         src="{% static 'fido/images/girl-dog.jpg' %}">
                </div>
                <div class="col-md-6 col-xl-5 text-center text-md-left">
                    <h2 class="h1 mb-5 font-weight-light">
                        Every pet,
                        <br>
                        <span class="font-weight-bold">deserves a home.</span>
                    </h2>
                    <p class="lead">
                        There are currently over two million animals in shelters in the United States, and that number
                        is growing by over a thousand each day. All animals awaiting adoption are examined, dewormed and
                        vaccinated against rabies.
                    </p>
                    <p class="lead">
                        If you are thinking about purchasing a pet, please consider adoption because every pet deserves
                        a forever home.
                    </p>
                    <img id="signature" src="{% static 'fido/images/signature.png' %}" alt="signature" class="mt-4">
                </div>
            </div>
        </div>
    </section>
    <div class="section section-md bg-soft">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8 text-center">
                    <span class="d-block mb-2">
                        <span class="star fas fa-star text-warning"></span>
                        <span class="star fas fa-star text-warning"></span>
                        <span class="star fas fa-star text-warning"></span>
                        <span class="star fas fa-star text-warning"></span>
                        <span class="star fas fa-star text-warning"></span>
                    </span>
                    <blockquote class="blockquote">
                        Thanks to Fido, we have a new family member.
                        It is exactly what our daughter dreamed of, big and furry!
                        <footer class="blockquote-footer mt-3 text-primary">Ivy Bailey</footer>
                    </blockquote>
                </div>
            </div>
        </div>
    </div>
    <div class="section section-sm py-0 mt-5 mt-md-n5 d-none d-md-block">
        <div class="container top-0 right-o left-0 z-2">
            <div class="row justify-content-center">
                <div class="col">
                    <div class="bg-white border border-light rounded-pill py-4">
                        <ul class="d-flex flex-wrap justify-content-center list-unstyled mb-0">
                            <li class="mx-xl-4 mx-3 d-flex align-items-center">
                                <h2 class="h5 m-0 mb-4 mb-md-0 text-gray">Our sponsors</h2>
                            </li>
                            <li class="mx-xl-4 mx-3 mb-3 mb-md-0">
                                <img class="img-fluid image-sm" src="{% static 'fido/images/paypal.svg' %}"
                                     alt="paypal logo">
                            </li>
                            <li class="mx-xl-4 mx-3 mb-3 mb-md-0">
                                <img class="img-fluid image-sm" src="{% static 'fido/images/airbnb.svg' %}"
                                     alt="airbnb logo">
                            </li>
                            <li class="mx-xl-4 mx-3 mb-3 mb-md-0">
                                <img class="img-fluid image-sm" src="{% static 'fido/images/forbes.svg' %}"
                                     alt="forbes logo">
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <section class="section section-md">
        <div class="container">
            <div class="row text-center justify-content-center">
                <div class="col-md-8 mb-5">
                    <h2>Frequently Asked Questions</h2>
                    <p class="lead">Find the answer to your question</p>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <div class="accordion" id="accordionExample1">
                        <div class="card card-sm card-body border-light mb-0">
                            <a href="#panel-1" data-target="#panel-1" class="accordion-panel-header collapsed"
                               data-toggle="collapse" role="button" aria-expanded="false" aria-controls="panel-1">
                                <span class="h6 mb-0 font-weight-bold">What is Fido?</span>
                                <span class="icon">
                                    <span class="fas fa-plus"></span>
                                </span>
                            </a>
                            <div class="collapse" id="panel-1">
                                <div class="pt-3">
                                    <p class="mb-0">
                                        Fido is a website connecting shelters with people willing to adopt. Its search
                                        engine makes it easy and fast to search among tens of thousands of cats and dogs
                                        by sex, breed, or location.
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="card card-sm card-body border-light mb-0">
                            <a href="#panel-2" data-target="#panel-2" class="accordion-panel-header collapsed"
                               data-toggle="collapse" role="button" aria-expanded="false" aria-controls="panel-2">
                                <span class="h6 mb-0 font-weight-bold">Is it free?</span>
                                <span class="icon">
                                    <span class="fas fa-plus"></span>
                                </span>
                            </a>
                            <div class="collapse" id="panel-2">
                                <div class="pt-3">
                                    <p class="mb-0">
                                        Yes, it is thanks to our sponsors - PayPal, Airbnb, and Forbes.
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="card card-sm card-body border-light">
                            <a href="#panel-3" data-target="#panel-3" class="accordion-panel-header"
                               data-toggle="collapse" role="button" aria-expanded="false" aria-controls="panel-3">
                                <span class="h6 mb-0 font-weight-bold">How can I help?</span>
                                <span class="icon">
                                    <span class="fas fa-plus"></span>
                                </span>
                            </a>
                            <div class="collapse" id="panel-3">
                                <div class="pt-3">
                                    <p class="mb-0">
                                        Currently, we do not need help with the site. If you would like to help, please
                                        volunteer at your local shelter.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="section py-0">
        <div class="container z-2">
            <div class="row position-relative justify-content-center align-items-center">
                <div class="col-12">
                    <div class="card border-light px-4 py-1">
                        <div class="card-body text-center text-md-left">
                            <div class="row align-items-center">
                                <div class="col-md-6">
                                    <h2 class="h1 mb-3">Representing a shelter?</h2>
                                    <p class="lead mb-4">
                                        Find out how our website can help you promote pets
                                        awaiting their new forever family.
                                    </p>
                                    <a href="{% url 'fido:for-shelters' %}" class="btn btn-primary">For Shelters</a>
                                </div>
                                <div class="col-12 col-md-6 mt-5 d-none d-md-block mt-md-0 text-md-center">
                                    <img src="{% static 'fido/images/doghouse.svg' %}" alt="doghouse">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

templates/fido/manage-pets.html
{% extends 'base.html' %}
{% load custom_tags_filters %}
{% block title %}
    Manage pets | {{ block.super }}
{% endblock title %}
{% block content %}
    <section class="section section-header pb-5 bg-primary text-white">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-xl-8 text-center">
                    <h1 class="display-2">Manage available pets</h1>
                    <p class="my-5">
                        or add a new
                        <a class="font-weight-bolder" href="{% url 'fido:new-cat' %}">cat</a>
                        or
                        <a class="font-weight-bolder" href="{% url 'fido:new-dog' %}">dog</a>.
                    </p>
                </div>
            </div>
        </div>
    </section>
    <section class="my-5" id="scroll-to-section">
        <div class="container">
            <div class="row justify-content-center pt-3 pb-4">
                <h1 class="display-4">Pets available at your shelter</h1>
            </div>
            <div class="row align-items-center">
                {% for pet in page_obj %}
                    <div class="col-6 col-md-4 col-lg-3 pt-4">
                        <div class="card">
                            <img src="{{ pet.photo.url }}" class="card-img-top rounded-top" alt="{{ pet }}">
                            <div class="card-body border border-light rounded-bottom border-top-0">
                                <span class="h6 icon-tertiary small">{{ pet.breed }}</span>
                                <h5 class="card-title mt-3">
                                    {{ pet }}
                                    <i class="fas {% if pet.sex == 'Male' %}fa-mars{% else %}fa-venus{% endif %} ml-2"></i>
                                </h5>
                                <p class="card-text">{{ pet.description|truncatechars:100 }}</p>
                                <a href="{% url pet|get_pet_url:'edit' pet.pk %}" target="_blank"
                                   class="btn btn-primary btn-sm mt-2 mr-2">
                                    <i class="fas fa-edit mr-1"></i>
                                    Edit
                                </a>
                                <a href="{% url pet|get_pet_url:'remove' pet.pk %}" class="btn btn-danger btn-sm mt-2">
                                    <i class="fas fa-trash-alt mr-1"></i>
                                    Remove
                                </a>
                            </div>
                        </div>
                    </div>
                {% empty %}
                    <div class="col-12 text-center mt-5">
                        <p>No results.</p>
                    </div>
                {% endfor %}
            </div>
            {% include 'fido/pagination.html' %}
        </div>
    </section>
    <script>
        if (window.location.search.includes('page')) {
            document.getElementById('scroll-to-section').scrollIntoView({behavior: 'smooth'});
        }
    </script>
{% endblock content %}