accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import forms, views

app_name = 'accounts'

urlpatterns = [
    path('privacy/', TemplateView.as_view(template_name='accounts/privacy.html'), name='privacy'),
    path('tos/', TemplateView.as_view(template_name='accounts/tos.html'), name='tos'),
    path('register/', views.register, name='register'),
    path(
        'login/',
        auth_views.LoginView.as_view(
            template_name='accounts/login.html',
            authentication_form=forms.LoginForm,
            redirect_authenticated_user=True,
            next_page='fido:new-shelter',
        ),
        name='login',
    ),
    path('logout/', auth_views.LogoutView.as_view(next_page='fido:homepage'), name='logout'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('fido.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = TemplateView.as_view(template_name='403.html')
handler404 = TemplateView.as_view(template_name='404.html')

fido/urls.py
from django.urls import path
from django.views.generic import TemplateView

from fido import views

app_name = 'fido'

urlpatterns = [
    path('', TemplateView.as_view(template_name='fido/index.html'), name='homepage'),
    path('for-shelters/', TemplateView.as_view(template_name='fido/for-shelters.html'), name='for-shelters'),
    path('contact/', views.contact, name='contact'),
    path('cat/<int:pk>/', views.cat_page, name='cat'),
    path('dog/<int:pk>/', views.dog_page, name='dog'),
    path('search/cats/', views.search_cats, name='search-cats'),
    path('search/dogs/', views.search_dogs, name='search-dogs'),
    path('search/cats/<slug:breed>/<slug:age>/<slug:sex>/<slug:shelter__shelteraddress__state>/',
         views.search_cats_params),
    path('search/dogs/<slug:breed>/<slug:age>/<slug:sex>/<slug:shelter__shelteraddress__state>/',
         views.search_dogs_params),
    path('shelter/<int:pk>/', views.shelter_page, name='shelter'),
    path('shelter/new/', views.new_shelter, name='new-shelter'),
    path('shelter/edit/', views.edit_shelter, name='edit-shelter'),
    path('shelter/remove/', views.remove_shelter, name='remove-shelter'),
    path('shelter/pets/', views.manage_pets, name='manage-pets'),
    path('shelter/cat/new/', views.new_cat, name='new-cat'),
    path('shelter/dog/new/', views.new_dog, name='new-dog'),
    path('shelter/cat/<int:pk>/edit/', views.edit_cat, name='edit-cat'),
    path('shelter/dog/<int:pk>/edit/', views.edit_dog, name='edit-dog'),
    path('shelter/cat/<int:pk>/remove/', views.remove_cat, name='remove-cat'),
    path('shelter/dog/<int:pk>/remove/', views.remove_dog, name='remove-dog'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Fido{% endblock title %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'fido/images/logo.svg' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/4.6.2/css/bootstrap.min.css"
          integrity="sha512-rt/SrQ4UNIaGfDyEXZtNcyWvQeOq0QLygHluFQcSjaGB04IxWhal71tKuzP6K8eYXYB6vJV4pHkXcmFGGQ1/0w=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css"
          integrity="sha512-0S+nbAYis87iX26mmj/+fWt1MmaKCv80H+Mbo+Ne7ES4I6rxswpfnC6PxmLiw33Ywj2ghbtTw0FkLbMWqh4F7Q=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link rel="stylesheet" href="{% static 'fido/pixel.min.css' %}">
    <link rel="stylesheet" href="{% static 'fido/style.css' %}">
</head>
<body>
{% block navbar %}
    <nav class="navbar sticky-top navbar-expand-lg navbar-transparent navbar-dark navbar-theme-primary">
        <div class="container position-relative">
            <a class="navbar-brand mr-lg-3" href="{% url 'fido:homepage' %}">
                <img class="navbar-brand-dark invert-colors" src="{% static 'fido/images/logo.svg' %}" alt="logo">
            </a>
            <div class="navbar-collapse collapse" id="navbar-default-primary">
                <div class="navbar-collapse-header">
                    <div class="row">
                        <div class="col-6 collapse-brand">
                            <a href="{% url 'fido:homepage' %}">
                                <img src="{% static 'fido/images/logo.svg' %}" alt="logo">
                            </a>
                        </div>
                        <div class="col-6 collapse-close">
                            <i class="fas fa-times" data-toggle="collapse" role="button"
                               data-target="#navbar-default-primary" aria-controls="navbar-default-primary"
                               aria-expanded="false" aria-label="Toggle navigation"></i>
                        </div>
                    </div>
                </div>
                <ul class="navbar-nav navbar-nav-hover align-items-lg-center ml-4">
                    <li class="nav-item dropdown">
                        <a class="nav-link" data-toggle="dropdown" aria-controls="adopt_submenu" aria-expanded="false"
                           aria-label="Toggle adopt submenu">
                            <span class="nav-link-inner-text ml-0">Adopt</span>
                            <span class="fas fa-angle-down nav-link-arrow ml-2"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-lg" id="adopt_submenu">
                            <div class="col-auto px-0" data-dropdown-content="">
                                <div class="list-group list-group-flush">
                                    <a href="{% url 'fido:search-dogs' %}"
                                       class="list-group-item list-group-item-action d-flex align-items-center p-0 py-3 px-lg-4">
                                        <span class="icon icon-sm icon-secondary">
                                            <span class="fas fa-dog"></span>
                                        </span>
                                        <div class="ml-4">
                                            <span class="text-dark d-block">Dog</span>
                                            <span class="small">Browse all dogs</span>
                                        </div>
                                    </a>
                                    <a href="{% url 'fido:search-cats' %}"
                                       class="list-group-item list-group-item-action d-flex align-items-center p-0 py-3 px-lg-4">
                                        <span class="icon icon-sm icon-primary">
                                            <span class="fas fa-cat"></span>
                                        </span>
                                        <div class="ml-4">
                                            <span class="text-dark d-block">Cat</span>
                                            <span class="small">Browse all cats</span>
                                        </div>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'fido:for-shelters' %}" class="nav-link">For Shelters</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'fido:contact' %}" class="nav-link">Contact</a>
                    </li>
                    {% if not request.user.is_authenticated %}
                        <li class="nav-item d-lg-none">
                            <a href="{% url 'accounts:register' %}" class="nav-link">Sign up</a>
                        </li>
                        <li class="nav-item d-lg-none">
                            <a href="{% url 'accounts:login' %}" class="nav-link">Log in</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
            {% if request.user.is_authenticated %}
                <div id="account-menu-container" class="dropdown">
                    <button class="btn dropdown-toggle" type="button" id="account-menu"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-2x fa-inverse fa-user-circle"></i>
                    </button>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="account-menu">
                        {% with shelter_pk=request.user.shelter.pk %}
                            {% if shelter_pk %}
                                <a class="dropdown-item" href="{% url 'fido:shelter' shelter_pk %}">My shelter</a>
                                <a class="dropdown-item" href="{% url 'fido:edit-shelter' %}">Manage shelter</a>
                                <a class="dropdown-item" href="{% url 'fido:manage-pets' %}">Manage pets</a>
                                <a class="dropdown-item" href="{% url 'fido:remove-shelter' %}">Remove shelter</a>
                            {% else %}
                                <a class="dropdown-item" href="{% url 'fido:new-shelter' %}">New shelter</a>
                            {% endif %}
                        {% endwith %}
                        <a class="dropdown-item" href="{% url 'accounts:logout' %}">Log out</a>
                    </div>
                </div>
            {% else %}
                <div class="d-none d-lg-block">
                    <div class="d-flex align-items-center">
                        <a href="{% url 'accounts:register' %}" class="btn btn-outline-white ml-md-3">Sign up</a>
                        <a href="{% url 'accounts:login' %}" class="btn btn-primary btn-white ml-md-3">
                            <i class="fas fa-sign-in-alt mr-2"></i>
                            Log in
                        </a>
                    </div>
                </div>
            {% endif %}
            <div class="d-flex align-items-center">
                <button class="navbar-toggler ml-2" type="button" data-toggle="collapse"
                        data-target="#navbar-default-primary" aria-controls="navbar-default-primary"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </div>
    </nav>
{% endblock navbar %}
{% block content %}{% endblock content %}
{% block footer %}
    <footer class="footer bg-primary text-white pb-6 pt-1 {% if request.path == '/' %}pt-7 mt-n7{% endif %}">
        <div class="container">
            <div class="row mt-6 justify-content-center pl-5 pl-sm-0">
                <div class="col-md-4 mr-3">
                    <p>
                        <strong>Fido</strong> is an online service that makes it easy to find adoptable dogs and cats
                        near you. It's free for both shelters and pet lovers.
                    </p>
                    <ul class="social-buttons mb-5 mb-lg-0">
                        <li>
                            <a href="https://twitter.com" target="_blank" rel="noreferrer nofollow"
                               class="icon icon-xs icon-white" aria-label="twitter social link">
                                <span class="fab fa-twitter"></span>
                            </a>
                        </li>
                        <li>
                            <a href="https://facebook.com" target="_blank" rel="noreferrer nofollow"
                               class="icon icon-xs icon-white" aria-label="facebook social link">
                                <span class="fab fa-facebook"></span>
                            </a>
                        </li>
                        <li>
                            <a href="https://instagram.com" target="_blank" rel="noreferrer nofollow"
                               class="icon icon-xs icon-white" aria-label="instagram social link">
                                <span class="fab fa-instagram"></span>
                            </a>
                        </li>
                        <li>
                            <a href="https://youtube.com" target="_blank" rel="noreferrer nofollow"
                               class="icon icon-xs icon-white" aria-label="youtube social link">
                                <span class="fab fa-youtube"></span>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="col-6 col-md-2 mb-5 mb-lg-0">
                    <h3 class="h5">Fido</h3>
                    <ul class="links-vertical">
                        <li><a href="{% url 'fido:homepage' %}">Homepage</a></li>
                        <li><a href="{% url 'fido:for-shelters' %}">For Shelters</a></li>
                        <li><a href="{% url 'fido:contact' %}">Contact</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md-2 mb-5 mb-lg-0">
                    <h3 class="h5">Adopt</h3>
                    <ul class="links-vertical">
                        <li><a href="{% url 'fido:search-dogs' %}">Dogs</a></li>
                        <li><a href="{% url 'fido:search-cats' %}">Cats</a></li>
                    </ul>
                </div>
            </div>
            <div class="row mt-2 mt-lg-6">
                <div class="col mb-md-0">
                    <a href="{% url 'fido:homepage' %}" class="d-flex justify-content-center">
                        <img src="{% static 'fido/images/logo.svg' %}" id="logo-footer" class="mb-3 invert-colors"
                             alt="logo">
                    </a>
                    <div class="d-flex text-center justify-content-center align-items-center" role="contentinfo">
                        <p class="font-weight-normal font-small mb-0">
                            Copyright &copy; Fido {% now 'Y' %}. All rights reserved.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
{% endblock footer %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.slim.min.js"
        integrity="sha512-eHWYortWe2NyxHIiY/wY82nK4RlPIDDDSD5ZvTHrTkiq9tAe++DBhq5rDcC02xqHxh0ctGGMbHKotqtYcYgXZA=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js"
        integrity="sha512-ubuT8Z88WxezgSqf3RLuNi5lmjstiJcyezx34yIU2gAHonIi27Na7atqzUZCOoY4CExaoFumzOsFQ2Ch+I/HCw=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/4.6.2/js/bootstrap.min.js"
        integrity="sha512-7rusk8kGPFynZWu26OKbTeI+QPoYchtxsmPeBqkHIEXJxeun4yJ4ISYe7C6sz9wdxeE1Gk3VxsIWgCZTc+vX3g=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</body>
</html>